In [3]:
import charge
import duplic_analisys
import origen_analisys
import controle_lotes
import output



df_periodo,df_trat,df_ficha,df_vivos,df_vivos_geral,df_origem_id,df_gacode,df_criterio,df_ls_batch,pst_egj,pst_out,df_mortalidade = charge.carregar_dados()

[2026-09-04 11:07:16.735241] [INFO] [Charge] ref usuario: luiz.farias
[2026-09-04 11:07:16.735241] [INFO] [Charge] ref periodo produtivo
[2026-09-04 11:07:16.735241] [INFO] [Charge] ref fichas fornecedor
[2026-09-04 11:07:16.735241] [INFO] [Charge] ref domicilios vivos
[2026-09-04 11:07:16.735241] [INFO] [Charge] ref prealocados fornecedor
[2026-09-04 11:07:16.735241] [INFO] [Charge] ref regionalizacao interna
do_rep7_pstools_br_2026-08-25_a_2026-09-23
[2026-09-04 11:07:16.735241] [INFO] [Charge] ref rep7: do_rep7_pstools_br_2026-08-25_a_2026-09-23
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref carregamento dados validação: PROD_VALIDACAO_FICHA_TC_2026-09

In [4]:

vl_atos_recrutamento = duplic_analisys.analise_duplicidade_e_crterio(df_trat,df_criterio,df_vivos,df_mortalidade)
vl_atos_recrutamento = duplic_analisys.analise_segmentacao_atos(vl_atos_recrutamento)

[2026-09-04 11:07:16.735241] [INFO] [processamento] ref normalização
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref analise duplicidade
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref atribuição duplicidade
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref cruzamento principal
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref cruzamento principal
***REVISÃO ENTRADA***
trat:  529
tl:  528
em:  527
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref faixas de atos (bins) e os rótulos de análise
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref base de retorno vl_atos_recrutamento (passagem)
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref obtensão dos dados de mortalidade
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref carregaameto dos atos recrutamento
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref criterio de comportamento exceão perfil aplicação
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref criterio de qualidade aplicação

In [5]:
df_ids_recrutados_origen_validacao = origen_analisys.origen_analisys(vl_atos_recrutamento, df_gacode,df_origem_id)
df_ids_recrutados_origen_validacao = origen_analisys.analise_segmentacao_origens(df_ids_recrutados_origen_validacao)

[2026-09-04 11:07:16.735241] [INFO] [processamento] ref criação de chaves de enriquecimento de dados
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref preparação base regionalização por setor
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref enriquecimento de bases vl_atos_recrutamento
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref limpeza de pre-segmentacao
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref separacao regioes nao pertencentes ao desenho amostral
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref separacao regioes nao pertencentes ao desenho amostral
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref seg aprovacao por origem
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref ajuste posterior origem
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref ajuste posterior origem
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref regra hard code linha 122 origen_analisys (revisar)
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref segmentação de bases para importação mediante regras
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref segmentação ajuste gacode para o time de qualidade amostral
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref decisão origem opicioanis são sempre pharma
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref segmentacao monoindividuo & nse

In [8]:
df_rct_batch_vivos_pend_importacao.Status.value_counts()

Series([], Name: count, dtype: int64)

In [11]:
df_ids_recrutados_origen_validacao['Status'].isna().value_counts()

Status
True    6061
Name: count, dtype: int64

In [6]:

df_rct_batch_vivos_pend_importacao = controle_lotes.controle_lotes(df_ids_recrutados_origen_validacao,df_ls_batch,df_periodo,df_vivos_geral)

output.arquivos_de_saida(df_rct_batch_vivos_pend_importacao,df_ficha,df_periodo,pst_egj,pst_out)

[2026-09-04 11:07:16.735241] [INFO] [processamento] ref processamento do ultimo lote de dados
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref identificacao data-entrada_gpm
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref geracao lote pendente do recrutamento para importação
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref separacao BACKLOG & ENVIADO_WP
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref aplicação periodo produtivo
[2026-09-04 11:07:16.735241] [INFO] [processamento] ref classificação de lotes & data de processamento
[2026-09-04 11:07:16.735241] [INFO] [output] ref identificacao fichas validadas
[2026-09-04 11:07:16.735241] [INFO] [output] ref regra hard code linha 18 (output.py) | lotes para não importar
[2026-09-04 11:07:16.735241] [INFO] [output] ref separação de fichas
[2026-09-04 11:07:16.735241] [INFO] [output] ref atualização detalhe validacao
[2026-09-04 11:07:16.735241] [INFO] [output] ref atualização overview
[2026-09-04 11:07:16.735241] [INFO] [output] ref atualização bolsa engajamento
[2026-09-04 11:07:16.735241] [INFO] [output] ref geração do arquivo final
[2026-09-04 11:07:16.735241] [INFO] [output] Arquivo 'C:\Users\luiz.farias\Numerator International\BKO - Documents\projeto-dados-ops\do_ficha\tc\output_validacao/PROD_VALIDACAO_FICHA_TC_2026-09.xlsx' criado com sucesso!

In [4]:
from datetime import datetime 
data_atual = datetime.now().strftime('%d%m%Y')

In [5]:
data_atual

'28082026'

In [3]:
str(pst_egj)

'C:\\Users\\luiz.farias\\Numerator International\\BKO - Documents\\projeto-dados-ops\\do_ficha\\tc\\output_engj'

In [7]:
import process
import os
from pathlib import Path
from process import logger

_, nm_arq = process.pegar_arquivo_recente(f'C:/Users/{dominio_interno}/Numerator International/BKO - Documents/projeto-dados-ops{pasta_output}', extensao=None,posicao=1)
logger.write( etapa='processamento', mensagem=f'ref carregamento dados validação: {nm_arq}')

df_ls_batch = process.carregamento(
        path= Path(datalake + pasta_output),
        prefixo=nm_arq,
        sh = 'Detalhe Validação'
)

[2026-08-27 15:47:28.897337] [INFO] [processamento] ref carregamento dados validação: PROD_VALIDACAO_FICHA_TC_2026-09

In [5]:
df_ls_batch

,Lote,Data_inicio_importacao,Status,dt_ficha,mes_produtivo_ficha,Decisao_Final,PanelSmart#1,qtd_indiv(P12a#1),Classe,Classific,...,Origem_importar,Duplicidade_de_Email,Duplicidade_de_Email.1,Duplicidade_de_Telefone,Duplicidade_de_Telefone.1,Validacao_Origem,saida_decisao,flag_complementar,data_processamento,arquivo_origem
0,Lote Processo Manual -2026-08-17,NaT,BACKLOG,NaT,NaN,GPM - FICHA IMPORTADA,552299393,1,6,MONO_INDIV&NSE_DE,...,4 - IHS,False,False,False,False,ORIGEM_CORRETA,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,NaN,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
1,Lote Processo Manual -2026-06-23,NaT,BACKLOG,NaT,NaN,GPM - FICHA IMPORTADA,552275840,6,5,NaN,...,20 - Nordeste,False,False,False,False,ORIGEM_CORRETA,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,NaN,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
2,NaN,NaT,BACKLOG,NaT,NaN,OFF - REGIÃO FORA DA COLETA,552281175,4,4,NaN,...,FORA DA COLETA,False,False,False,False,SETOR_NAO_CONTEMPLADO,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,NaN,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
3,Lote Processo Manual -2026-08-17,NaT,BACKLOG,NaT,NaN,GPM - FICHA IMPORTADA,552298125,10,2,NaN,...,4 - IHS,False,False,False,False,ORIGEM_CORRETA,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,NaN,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
4,Lote Processo Manual -2026-07-30,NaT,BACKLOG,NaT,NaN,GPM - FICHA IMPORTADA,552282458,1,1,MONO_INDIV,...,20 - Nordeste,False,False,False,False,ORIGEM_CORRETA,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,NaN,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,GPM_20260826_140605,2026-08-26 14:06:05.485,ENVIADO_WP,2026-08-25,2026-09,SUBIR GPM,552298815,3,6,NSE_DE,...,4 - IHS,False,False,False,False,ORIGEM_CORRETA,OK_25_ATOS,NaN,2026-08-26 14:06:05.484778,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
282,GPM_20260825_093238,2026-08-25 09:32:38.751,ENVIADO_WP,2026-08-25,2026-09,GPM - FICHA IMPORTADA,552290585,1,3,MONO_INDIV,...,22 - Centro-Oeste,False,False,False,False,ORIGEM_CORRETA,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,2026-08-25 09:32:38.750625,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
283,GPM_20260826_140605,2026-08-26 14:06:05.485,ENVIADO_WP,2026-08-25,2026-09,SUBIR GPM,552299695,2,6,NSE_DE,...,4 - IHS,False,False,False,False,ORIGEM_CORRETA,OK_25_ATOS,NaN,2026-08-26 14:06:05.484778,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
284,GPM_20260826_140605,2026-08-26 14:06:05.485,ENVIADO_WP,2026-08-26,2026-09,SUBIR GPM - CRITERIO DE QUALIDADE (<25 ATOS),552298811,1,5,MONO_INDIV,...,4 - IHS,False,False,False,False,ORIGEM_CORRETA,AGUARDAR,NAO_CUMPRE_CRITERIO_QUALIDADE,2026-08-26 14:06:05.484778,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx
285,GPM_20260827_083133,2026-08-27 08:31:33.052,ENVIADO_WP,2026-08-26,2026-09,SUBIR GPM,552299647,2,5,NaN,...,4 - IHS,False,False,False,False,ORIGEM_CORRETA,OK_25_ATOS,NaN,2026-08-27 08:31:33.051989,PROD_VALIDACAO_FICHA_TC_2026-09.xlsx

# 1. Imports 
Principais dependências:
1. atm_tc: importar pacote de funções;
2. Panmdas: Instalação via pip;

In [21]:
# Resolinção de root file
from pathlib import Path
import sys
import pandas as pd

In [22]:
# Define a raiz do projeto
ROOT = Path.cwd().parent  # ajuste conforme sua estrutura

# adiciona no PATH do Python
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

print(ROOT)

c:\Users\luiz.farias\OneDrive - Numerator International\Área de Trabalho\Workspace\PROD

In [23]:
def obter_periodo_produtivo(data, periodo):
    linha = periodo.loc[
        (periodo["Desde"] <= data) &
        (periodo["Hasta"] >= data)
    ]

    if not linha.empty:
        ano = linha.iloc[0]["Ano"]
        mes = linha.iloc[0]["Mes"]
        return f"{ano}-{mes:02d}"  # Ex.: 2026-07

    return pd.NA

In [24]:
def tel_number_pdr_val(df, col1):

    import pandas as pd

    df = df.copy()

    nm = 'Telefone_NRZD'

    df[nm] = (
        df[col1]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", "", regex=True)
        .str.replace(r"[^\d]", "", regex=True)
    )

    # Remove código do país apenas quando fizer sentido
    df[nm] = df[nm].apply(
        lambda x: x[2:] if x.startswith("55") and len(x) >= 12 else x
    )

    # Remove zeros à esquerda DEPOIS
    df[nm] = df[nm].str.replace(r"^0+", "", regex=True)

    return df

In [25]:
def email_pdr_val(df, col1):

    import pandas as pd

    df = df.copy()

    nm = 'Email_NRZD'

    # Normalização
    df[nm] = (
        df[col1]
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(r'\s+', '', regex=True)
    )

    # Validação da estrutura
    email_regex = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

    df['em_validacao'] = (
        df[nm]
        .str.match(email_regex, na=False)
    )

    return df

In [26]:
def carregamento(prefixo, path, hd=None,fluxo_externo=False,sn=None):
    import pandas as pd
    import glob
    import os

    arquivos = (
        glob.glob(os.path.join(path, f"{prefixo}*.csv"))
        + glob.glob(os.path.join(path, f"{prefixo}*.xlsx"))
        + glob.glob(os.path.join(path, f"{prefixo}*.xls"))
    )

    dfs = []

    for arq in arquivos:

        extensao = os.path.splitext(arq)[1].lower()

        if extensao == ".csv":
            df = pd.read_csv(arq, sep=';', low_memory=False)

        elif extensao in [".xlsx", ".xls"]:
            if hd is None:
                if sn is None:
                    df = pd.read_excel(arq)  # primeira aba
                else:
                    df = pd.read_excel(arq, sheet_name=sn)
            else:
                if sn is None:
                    df = pd.read_excel(arq, header=hd)  # primeira aba
                else:
                    df = pd.read_excel(arq, header=hd, sheet_name=sn)

        else:
            continue

        # Sempre guarda a origem
        df['arquivo_origem'] = os.path.basename(arq)

        dfs.append(df)

    if not dfs:
        raise ValueError("Nenhum arquivo encontrado para o prefixo informado.")


    df_final = pd.concat(dfs, ignore_index=True)

    # Remove apenas no fluxo externo
    if fluxo_externo:
        df_final.drop(columns='arquivo_origem', inplace=True)

    return df_final

# 2. Carregamento de dados
- datalake: C:\Users\luiz.farias\Numerator International\BKO - projeto-dados-ops;
- pasta_ficha: ...\do_ficha\tc;
- pasta_domicilios: ...\do_domicilios_vivos;
- pasta_all:pre: ...\do_preal_fornecedor\ref_cosolidado;
- pasta_dogacode: ...\do_gacode;
- pasta_bolsa_engaj: ...\do_ficha\tc\output\engj

## 2.2 Carregamento de bases principais

In [27]:
# Pasta raiz do projets

# Trocar para domínio interno do pc pessoal
dominio_interno = 'luiz.farias'

# Pasta MASTER
datalake = f'C:/Users/{dominio_interno}/Numerator International/BKO - Documents/projeto-dados-ops'

# Pasta Dominio Interno
pasta_ficha = '/do_ficha/tc/input_bruto'
pasta_domicilios = '/do_bases/TopClient'
pasta_all_pre = '/do_preal_fornecedor/ref_cosolidado'
pasta_gacode = '/do_gacode'
pasta_output = '/do_ficha/tc/output_validacao'
pasta_per_produtivo = '/do_calendario_fiscal'
pasta_engj ='/do_ficha/tc/output_engj'

In [28]:
# Ficha de cadastro do panelista
df_periodo= carregamento(    
    path = Path(datalake + pasta_per_produtivo),
    prefixo = 'do_cal'
)

In [29]:
df_periodo['Desde'] = pd.to_datetime(df_periodo['Desde'])
df_periodo['Hasta'] = pd.to_datetime(df_periodo['Hasta'])

In [30]:
# Ficha de cadastro do panelista
df_base= carregamento(    
    path = Path(datalake + pasta_output),
    prefixo = 'PROD_VALIDACAO',
    sn= 'Detalhe Validação'
    
)

In [31]:
# Domicilios Vivos
df_vivos = carregamento(
    path = Path(datalake + pasta_domicilios),
    prefixo = 'NRPerfilDomicilio',
    hd = 14,
    sn=None

)
df_vivos.rename(columns={'FIPanel1':'Data_Entrada'}, inplace=True)
df_vivos.iddomicilio = df_vivos.iddomicilio.astype(str)
df_vivos_geral = df_vivos[['iddomicilio', 'Data_Entrada','Origen Proveedor']].copy()

# 3. Revisão Origens

## 3.1 Normalização

In [32]:
from unidecode import unidecode

df_base.drop_duplicates(subset='PanelSmart#1',inplace=True)
df_vivos.iddomicilio = df_vivos.iddomicilio.astype(str)
df_base['PanelSmart#1'] = df_base['PanelSmart#1'].astype(str)
df_vivos['Desc GAC_adj'] = (df_vivos['Desc GAC']
                            .str.replace(r'^BR-', '', regex=True)
                            .str.lower()
                            .apply(unidecode)
                            .str.replace(r'[^\w\s-]', '', regex=True))   # Remove pontuação)

df_base['chave_setor'] = (df_base['chave_setor']
                            .str.replace(r'^BR-', '', regex=True)
                            .str.lower()
                            .str.replace(r'[^\w\s-]', '', regex=True))

In [54]:
vl = df_vivos[['iddomicilio','Origen Proveedor','Data_Entrada','Desc GAC_adj','Origen Hogar']].merge(df_base[['PanelSmart#1', 'chave_setor','Pre_Origen','Origem_importar']], 
                                                                                     left_on='iddomicilio',
                                                                                 right_on='PanelSmart#1',
                                                                                 how='inner')

In [55]:
vl['Origen Hogar'] = (
    vl['Origen Hogar']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)
map_origem = {
    'Mirror Nuevo Reclutado': '4 - IHS',
    'Expansión Nordeste': '20 - Nordeste',
    'Expansión Interior SP': '21 - Interior SP',
    'Expansión Centro-Oeste': '22 - Centro-Oeste',
    'Expansión Resto BR': '23 - Resto BR'
}

vl['Origen Hogar_norm'] = vl['Origen Hogar'].map(map_origem)

In [56]:
vl['validação setor'] = vl['Desc GAC_adj'] == vl['chave_setor']
vl['validação origen'] = vl['Origem_importar'] == vl['Origen Hogar_norm']

# 3.2 Analise

In [57]:
vl['Data_Entrada'] = pd.to_datetime(vl['Data_Entrada'], dayfirst=True)

In [58]:
vl['mes_produtivo'] = vl['Data_Entrada'].apply(
    lambda x: obter_periodo_produtivo(x, df_periodo))

In [59]:
vl.loc[vl.mes_produtivo == '2026-08'].groupby(['mes_produtivo'])['validação origen'].value_counts().unstack(fill_value=0)

validação origen  False  True
mes_produtivo
2026-08             135   1224

In [61]:
vl.loc[vl.mes_produtivo == '2026-08'].groupby(['mes_produtivo','Data_Entrada'])['validação origen'].value_counts().unstack(fill_value=0).reset_index()

validação origen mes_produtivo Data_Entrada  False  True
0                      2026-08   2026-07-27     58   155
1                      2026-08   2026-07-28      6    84
2                      2026-08   2026-07-29     71   367
3                      2026-08   2026-07-30      0   174
4                      2026-08   2026-07-31      0    38
5                      2026-08   2026-08-04      0   234
6                      2026-08   2026-08-06      0   172

In [49]:
vl.loc[(vl.Data_Entrada == '2026-08-06') & (vl['validação origen'] == False)]

,iddomicilio,Origen Proveedor,Data_Entrada,Desc GAC_adj,Origen Hogar,PanelSmart#1,chave_setor,Pre_Origen,Origem_importar,Origen Hogar_norm,validação setor,validação origen,mes_produtivo
23975,552302830,NaN,2026-08-06,sul-rio grande do sul-viamao,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23976,552302831,NaN,2026-08-06,sul-rio grande do sul-viamao,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23977,552302832,NaN,2026-08-06,sudeste-sao paulo-campinas,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23978,552302833,NaN,2026-08-06,sudeste-sao paulo-sao paulo-jardim angela,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23979,552302834,NaN,2026-08-06,centro-oeste-goias-santa helena de goias,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23980,552302835,NaN,2026-08-06,sul-santa catarina-sao jose,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23981,552302836,NaN,2026-08-06,sul-santa catarina-sao jose,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23982,552302837,NaN,2026-08-06,sul-santa catarina-sao jose,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23983,552302838,NaN,2026-08-06,sul-rio grande do sul-viamao,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08
23984,552302839,NaN,2026-08-06,sudeste-minas gerais-contagem,IBS,NaN,NaN,NaN,NaN,NaN,False,False,2026-08

In [46]:
vl.loc[(vl['validação origen'] == False) & (vl['mes_produtivo'] == '2026-08') & (vl['Origem_importar'] == '21 - Interior SP')]['Origen Hogar_norm'].value_counts()

Origen Hogar_norm
4 - IHS    3
Name: count, dtype: int64

In [ ]:
vl.loc[(vl['validação origen'] == False) & (vl['mes_produtivo'] == '2026-08') & (vl['Origem_importar'] == '4 - IHS')]['Origen Hogar_norm'].value_counts()

Origen Hogar_norm
20 - Nordeste        92
22 - Centro-Oeste     2
Name: count, dtype: int64

In [ ]:
vl.loc[(vl['validação origen'] == False) & (vl['mes_produtivo'] == '2026-08') & (vl['Origem_importar'] == '23 - Resto BR')]['Origen Hogar_norm'].value_counts()

Origen Hogar_norm
4 - IHS    36
Name: count, dtype: int64